server:
  port: 11000
logging:
  level:
    com.eddie.mall_coupon: debug

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.199.181:3306/project_mall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: cloud-mall-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  type-aliases-package: com.eddie.mall_order.entity
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0