#server:
#  port: 9000
#logging:
#  level:
#    com.atguigu.gulimall: debug
#
#spring:
#  profiles:
#    active: dev
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.199.144:3306/project_mall_ums
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#  application:
#    name: cloud-mall-member
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#
#mybatis-plus:
#  type-aliases-package: com.eddie.mall_member.entity
#  mapper-locations: classpath:mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#
#member:
#  username: EddieZhang
#  major: Java